### ISSUE TITLE
使用问题及功能建议

### ISSUE THREAD

**Issue by okoling** [hanc00l/nemo_go#63]
作者你好，给nemo_go点个赞！
下面有一些使用上的问题，劳烦解答
1. Dirsearch 里面的扫描字典如何自定义呢？
![image](https://user-images.githubusercontent.com/90396284/209965981-64196b00-d6d4-4f23-aba5-66fbec16806c.png)
2. 支持数据库爆破模块、例如单独拿一批redis、mysql出来爆破
3. fofa、quake、hunter apikey是否能在界面中配置及测试是否可用？
4. 导入离线资产的文件格式有说明吗，支持导入哪些格式？想自己扩展如何扩展呢
![image](https://user-images.githubusercontent.com/90396284/209967408-3d00d020-56d1-49ef-a809-5b85e3d75d89.png)
5. 漏洞验证模块支持ip:port端口批量扫描吗？
![image](https://user-images.githubusercontent.com/90396284/209967723-c8376d46-9dde-47a2-ae75-f0850807558e.png)
6. 按照[docker安装方法](https://github.com/hanc00l/nemo_go/blob/main/docs/docker.md)，修改好conf/worker.yml文件
```
root@scan:~/nemo/conf# cat worker.yml
rpc:
  host: 199.199.199.199
  port: 5001
  authKey: ZduibTKhc
fileSync:
  host: 199.199.199.199
  port: 5002
  authKey: ZduibTKhc
rabbitmq:
  host: 199.199.199.199
  port: 5672
  username: nemo
  password: nemo2022

```
启动`docker-compose -f docker-compose.worker.yml up -d --scale worker=6`，发现每个worker启动连接的是127.0.0.1
![image](https://user-images.githubusercontent.com/90396284/209970200-3f3a5948-e2d5-4952-a9c2-98ea6ea952ec.png)
